### ISSUE TITLE
This map does not have an element with the key "null_command_unix"

### ISSUE THREAD

**Issue by DevopsMercenary** [Invicton-Labs/terraform-external-shell-resource#10]
I've been using this extension for a while, today I started getting these errors.  I tried deleting the entire `.terraform` folder to get all fresh and the results were the same as below

Not sure what has changed.  Here's some of my setup...

```
[greg@CM-LT-0007 pii-leaf-vm (main *%)]$ terraform --version
Terraform v1.3.8
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azuread v2.36.0
+ provider registry.terraform.io/hashicorp/azurerm v3.48.0
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

Here's what terraform is downloading for the extension...

```
Downloading registry.terraform.io/Invicton-Labs/shell-resource/external 0.4.0 for tags.shell-hostname...
- tags.shell-hostname in .terraform/modules/tags.shell-hostname
Downloading registry.terraform.io/Invicton-Labs/shell-data/external 0.4.2 for tags.shell-hostname.delete_files...
- tags.shell-hostname.delete_files in .terraform/modules/tags.shell-hostname.delete_files
Downloading registry.terraform.io/Invicton-Labs/shell-data/external 0.4.2 for tags.shell-hostname.write_command_files...
- tags.shell-hostname.write_command_files in .terraform/modules/tags.shell-hostname.write_command_files
```

Here's the code

```
module "shell-hostname" {

  source = "Invicton-Labs/shell-resource/external"

  command_unix = "hostname"
}
```

The error

```
╷
│ Error: Missing map element
│
│   on .terraform/modules/tags.shell-hostname/main.tf line 285, in resource "null_resource" "shell":
│  285:       self.triggers.command_destroy_unix == self.triggers.null_command_unix ? [
│     ├────────────────
│     │ self.triggers is map of string with 21 elements
│
│ This map does not have an element with the key "null_command_unix".
╵
╷
│ Error: Missing map element
│
│   on .terraform/modules/tags.shell-hostname/main.tf line 294, in resource "null_resource" "shell":
│  294:       dirname("/") == "\\" ? self.triggers.command_destroy_windows == self.triggers.null_command_windows : self.triggers.command_destroy_unix == self.triggers.null_command_unix
│     ├────────────────
│     │ self.triggers is map of string with 21 elements
│
│ This map does not have an element with the key "null_command_unix".
```

**Comment by DevopsMercenary** [comment]
Trying out the REadme's sample `module "shell_resource_hello" {`

I've noticed that in version 0.3.3 the output I receive is

```
Outputs:

exitstatus = 0
stderr = <<EOT


EOT
stdout = <<EOT
Hello World from 2023-03-21T12:49:20Z

EOT
```

BUT for the output of v0.4.0

```
Outputs:

exitstatus = 0
stderr = ""
stdout = "Hello  from "
```

Maybe I just need to figure out how to move to v0.4.0

**Comment by DevopsMercenary** [comment]
I've seen this before, but not sure how to explain it or what it's called.

The problem is that my existing terraform state is for v0.3.3.  If I switch to using v0.4.0 then there is something about the existing state the new version doesn't like.  I guess the v0.4.0 expects to see an `null_command_unix` in the existing state but the v0.3.3 doesn't store.

To solve this. I removed all references to any modules that was using `source = "Invicton-Labs/shell-resource/external"`

ran a `terraform apply` which then deleted any existing state for the module,

Then re-enabled my modules and performed a `terraform apply`

Probably some other or better ways to do this too.

Please do with this issue as you desire.

**Comment by KyleKotowick** [comment]
Sorry, I just read through this today. As soon as I saw the title, I knew the issue, and it looks like you identified it too.

0.4.x is not backwards-compatible with 0.3.x. The easiest fix is to do a `terraform state rm` of the old module and let it re-run the external code. I'll add a comment about that in the release notes.
