### ISSUE TITLE
Reference returned ID in destroy.

### ISSUE THREAD

**Issue by karlschriek** [Invicton-Labs/terraform-external-shell-resource#5]
This module is a great workaround, thanks for putting in the work!

I am trying to implement a simple workflow with the Azure CLI to create/destroy resources that have not been implemented in the official Azure terraform provider yet.

Basically I want to perform a post to an API, which returns a JSON.

I.e. to `create`:

ORGA="my-orga"
NAME="PAT"

az rest \
--method post  \
--uri "https://vssps.dev.azure.com/${ORGA}/_apis/Tokens/Pats?pi-version=7.1-preview.1"  \
--resource "https://management.core.windows.net/"  \
--body '{ "displayName": "'$NAME'" , "scope": "Read" }'  \
--headers Content-Type=application/json 

The returned output looks like:

```
OUTPUT='{
  "patToken": {
    "authorizationId": "71bdc7b3-dbfe-4649-bb85-c03710057e67",
    "displayName": "PAT",
    "scope": "Read",
    "targetAccounts": [
      "a3fbd8cc-4b0e-4a80-93b4-54ee2e30ee94"
    ],
    "token": "g5ffffffffffffffffffffffggggggggggggggggggeeeeeeeeeeeee",
    "validFrom": "2022-04-20T12:27:48.8Z",
    "validTo": "2023-04-20T12:27:48.8Z"
  },
  "
```

Which I can parse out like:

```
TOKEN=$(echo $OUTPUT | jq -r .patToken.token)
AUTH_ID=$(echo $OUTPUT | jq -r .patToken.authorizationId)
```

I need to be able to get back two values here:
1. The `TOKEN`, which I need for downstream purposes and can simply return as an `output` 
2. The `AUTH_ID` (which I need in order to destroy the token).

The `AUTH_ID` is the part I need help with. I need access to this ID when calling destroy, which looks something like:

```
az rest \
--method delete  \
--uri "https://vssps.dev.azure.com/${ORGA}/_apis/tokens/pats?authorizationId=${AUTH_ID}&api-version=7.1-preview.1"  \
--resource "https://management.core.windows.net/"
```

So I need to persist the `AUTH_ID` somehow and then use it when calling destroy.

**Comment by KyleKotowick** [comment]
Hi, I'm not quite clear on what you're asking. Are you asking how you would retrieve `authorizationId`, or how you would use it in the destruction?

**Comment by karlschriek** [comment]
How would I persist `authorizationId` during create and then use it when running destroy?

**Comment by KyleKotowick** [comment]
Unfortunately, that's not possible. Terraform requires destroy provisioners to be defined at the time that a resource is created (see the [destroy-time provisioner documentation](https://www.terraform.io/language/resources/provisioners/syntax#destroy-time-provisioners). This means that you can't modify the destroy command after the resource is created.

To achieve your goal, perhaps you can find some sort of `list` command or similar that can find the `authorizationId` at destroy-time, based on tags or something similar?

**Comment by karlschriek** [comment]
That's what I was afraid of, thanks for confirming.

I have only an inexact workaround, which is to delete all tokens that have the declared `displayName`, but since that is not unique it will also delete others. I can live with it though.

It is quite a pity that destroy-time provisioners doesn't support this, since I think this is quite a typical approach when using CLIs (which seem to be a nice candidate for wrapping with a shell resource). I.e., use CLI to send a POST request and create a resource, get the unique id of the resource back in the response. Parse out the ID and use that for all further interactions with the resource.

**Comment by KyleKotowick** [comment]
Since there is no way to deal with this that is supported in Terraform, I'll close this issue.
