### ISSUE TITLE
run.sh does not execute on debian

### ISSUE THREAD

**Issue by moosbruggerj** [Invicton-Labs/terraform-external-shell-resource#7]
Hello,

When using the shell resource on a debian machine, the run.sh script fails with an exit code of 2.
It does not create any files, neither stdout, stderr, nor debug.
The source seems to be the `set -o pipefail` line.
If that line is removed, the script executes at least until the tobool function definiton.
The underlying problem seems to be, that the script is not POSIX shell compatible and therefore cannot be correctly executed by dash, which is the default `/bin/sh` implementation on debian 11.

Tested on debian 11 bullseye with dash 0.5.11.
Reverting back to an older release, which uses bash is not an option for me, because the same terraform configuration must also run in a busybox environment without bash.
Tangentially, the run.sh script uses hard coded bash calls internally, which is an issue on busybox environments without bash.

Currently I see two ways forward. One is to make the whole script POSIX compatible, the other is to make the shell configurable with terraform variables.

I would be happy to provide pull requests, if so desired.

**Comment by nadworny** [comment]
same on macos 12.4 :(

**Comment by KyleKotowick** [comment]
This, and other compatibility issues, has now been resolved in release v0.4.0. Please try it out and report any issues you find.
